/**
 * Product catalogue — generated from the approved design canvas asset tree.
 *
 * Names were normalised from the source filenames: pt-BR spelling and accents
 * corrected, units spaced ("1Kg" -> "1 kg"), and title-cased with Portuguese
 * minor words kept lowercase. `image` points at the WebP packshot under
 * `public/images/products/`, generated by `scripts/optimize-product-images.mjs`.
 */

export interface ProductFamily {
	readonly slug: string;
	readonly name: string;
	readonly count: number;
}

export interface Product {
	readonly slug: string;
	readonly name: string;
	readonly familySlug: string;
	readonly family: string;
	readonly image: string;
}

export const PRODUCT_FAMILIES: readonly ProductFamily[] = [
	{
		slug: "chas",
		name: "Chás",
		count: 26,
	},
	{
		slug: "ervas-e-especiarias",
		name: "Ervas e Especiarias",
		count: 8,
	},
	{
		slug: "farinhas-naturais",
		name: "Farinhas Naturais",
		count: 6,
	},
	{
		slug: "institucional",
		name: "Institucional",
		count: 18,
	},
	{
		slug: "molhos-e-pastas",
		name: "Molhos e Pastas",
		count: 7,
	},
	{
		slug: "sementes-e-graos-naturais",
		name: "Sementes e Grãos Naturais",
		count: 7,
	},
	{
		slug: "temperos-em-po",
		name: "Temperos em Pó",
		count: 17,
	},
	{
		slug: "temperos-liquidos-prontos",
		name: "Temperos Líquidos Prontos",
		count: 16,
	},
] as const;

export const PRODUCTS: readonly Product[] = [
	{
		slug: "melissa",
		name: "Melissa",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-melissa.webp",
	},
	{
		slug: "carqueja-amarga",
		name: "Carqueja Amarga",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-carqueja-amarga.webp",
	},
	{
		slug: "espinheira-santa",
		name: "Espinheira Santa",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-espinheira-santa.webp",
	},
	{
		slug: "boldo",
		name: "Boldo",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-boldo.webp",
	},
	{
		slug: "camomila",
		name: "Camomila",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-camomila.webp",
	},
	{
		slug: "capim-limao",
		name: "Capim Limão",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-capim-limao.webp",
	},
	{
		slug: "cavalinha",
		name: "Cavalinha",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-cavalinha.webp",
	},
	{
		slug: "cha-acalma",
		name: "Chá Acalma",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-cha-acalma.webp",
	},
	{
		slug: "cha-antigripal",
		name: "Chá Antigripal",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-cha-antigripal.webp",
	},
	{
		slug: "cha-da-vida",
		name: "Chá da Vida",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-cha-da-vida.webp",
	},
	{
		slug: "cha-rins-e-bexiga",
		name: "Chá Rins e Bexiga",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-cha-rins-e-bexiga.webp",
	},
	{
		slug: "cha-sono-bom",
		name: "Chá Sono Bom",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-cha-sono-bom.webp",
	},
	{
		slug: "cha-verde",
		name: "Chá Verde",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-cha-verde.webp",
	},
	{
		slug: "erva-cidreira",
		name: "Erva Cidreira",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-erva-cidreira.webp",
	},
	{
		slug: "erva-doce",
		name: "Erva Doce",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-erva-doce.webp",
	},
	{
		slug: "folha-de-amora",
		name: "Folha de Amora",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-folha-de-amora.webp",
	},
	{
		slug: "folha-de-eucalipto",
		name: "Folha de Eucalipto",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-folha-de-eucalipto.webp",
	},
	{
		slug: "folha-de-maracuja",
		name: "Folha de Maracujá",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-folha-de-maracuja.webp",
	},
	{
		slug: "hibisco",
		name: "Hibisco",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-hibiscus.webp",
	},
	{
		slug: "hortela",
		name: "Hortelã",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-hortela.webp",
	},
	{
		slug: "folha-de-insulina",
		name: "Folha de Insulina",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-insulina-folha.webp",
	},
	{
		slug: "seca-barriga",
		name: "Seca Barriga",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-seca-barriga.webp",
	},
	{
		slug: "sene",
		name: "Sene",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-sene.webp",
	},
	{
		slug: "unha-de-gato",
		name: "Unha de Gato",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-unha-de-gato.webp",
	},
	{
		slug: "uxi-amarelo",
		name: "Uxi Amarelo",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/sachet-uxi-amarelo.webp",
	},
	{
		slug: "mulungu",
		name: "Mulungu",
		familySlug: "chas",
		family: "Chás",
		image: "/images/products/chas/scachet-mulungu.webp",
	},
	{
		slug: "alecrim",
		name: "Alecrim",
		familySlug: "ervas-e-especiarias",
		family: "Ervas e Especiarias",
		image: "/images/products/ervas-e-especiarias/sachet-alecrim.webp",
	},
	{
		slug: "cominho-em-graos",
		name: "Cominho em Grãos",
		familySlug: "ervas-e-especiarias",
		family: "Ervas e Especiarias",
		image: "/images/products/ervas-e-especiarias/sachet-cominho-em-graos.webp",
	},
	{
		slug: "cravo-da-india",
		name: "Cravo da Índia",
		familySlug: "ervas-e-especiarias",
		family: "Ervas e Especiarias",
		image: "/images/products/ervas-e-especiarias/sachet-cravo-da-india.webp",
	},
	{
		slug: "louro",
		name: "Louro",
		familySlug: "ervas-e-especiarias",
		family: "Ervas e Especiarias",
		image: "/images/products/ervas-e-especiarias/sachet-louro.webp",
	},
	{
		slug: "oregano",
		name: "Orégano",
		familySlug: "ervas-e-especiarias",
		family: "Ervas e Especiarias",
		image: "/images/products/ervas-e-especiarias/sachet-oregano.webp",
	},
	{
		slug: "pimenta-calabresa",
		name: "Pimenta Calabresa",
		familySlug: "ervas-e-especiarias",
		family: "Ervas e Especiarias",
		image: "/images/products/ervas-e-especiarias/sachet-pimenta-calabresa.webp",
	},
	{
		slug: "pimenta-em-graos",
		name: "Pimenta em Grãos",
		familySlug: "ervas-e-especiarias",
		family: "Ervas e Especiarias",
		image: "/images/products/ervas-e-especiarias/sachet-pimenta-em-graos.webp",
	},
	{
		slug: "salsa",
		name: "Salsa",
		familySlug: "ervas-e-especiarias",
		family: "Ervas e Especiarias",
		image: "/images/products/ervas-e-especiarias/sachet-salsa.webp",
	},
	{
		slug: "farinha-de-beterraba",
		name: "Farinha de Beterraba",
		familySlug: "farinhas-naturais",
		family: "Farinhas Naturais",
		image:
			"/images/products/farinhas-naturais/sachet-farinha-de-beterraba.webp",
	},
	{
		slug: "farinha-de-uva",
		name: "Farinha de Uva",
		familySlug: "farinhas-naturais",
		family: "Farinhas Naturais",
		image: "/images/products/farinhas-naturais/sachet-farinha-de-uva.webp",
	},
	{
		slug: "gengibre-em-po",
		name: "Gengibre em Pó",
		familySlug: "farinhas-naturais",
		family: "Farinhas Naturais",
		image: "/images/products/farinhas-naturais/sachet-gengibre-po.webp",
	},
	{
		slug: "guarana-em-po",
		name: "Guaraná em Pó",
		familySlug: "farinhas-naturais",
		family: "Farinhas Naturais",
		image: "/images/products/farinhas-naturais/sachet-guarana-em-po.webp",
	},
	{
		slug: "maca-peruana",
		name: "Maca Peruana",
		familySlug: "farinhas-naturais",
		family: "Farinhas Naturais",
		image: "/images/products/farinhas-naturais/sachet-maca-peruana.webp",
	},
	{
		slug: "psyllium",
		name: "Psyllium",
		familySlug: "farinhas-naturais",
		family: "Farinhas Naturais",
		image: "/images/products/farinhas-naturais/sachet-psyllium.webp",
	},
	{
		slug: "amaciante-de-carne-1-kg",
		name: "Amaciante de Carne 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/amaciante-de-carne-1kg.webp",
	},
	{
		slug: "coloral-1-kg",
		name: "Coloral 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/coloral-1kg.webp",
	},
	{
		slug: "cominho-em-po-1-kg",
		name: "Cominho em Pó 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/cominho-em-po-1kg.webp",
	},
	{
		slug: "farinha-de-aveia-1-kg",
		name: "Farinha de Aveia 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/farinha-de-aveia-1kg.webp",
	},
	{
		slug: "folha-de-louro-1-kg",
		name: "Folha de Louro 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/folha-de-louro-1kg.webp",
	},
	{
		slug: "oregano-1-kg",
		name: "Orégano 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/oregano-1kg.webp",
	},
	{
		slug: "paprica-picante-1-kg",
		name: "Páprica Picante 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/paprica-picante-1kg.webp",
	},
	{
		slug: "paprica-defumada-1-kg",
		name: "Páprica Defumada 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/paprica-defumada-1kg.webp",
	},
	{
		slug: "paprica-doce-1-kg",
		name: "Páprica Doce 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/paprica-doce-1kg.webp",
	},
	{
		slug: "tempero-para-frango-1-kg",
		name: "Tempero para Frango 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/temepero-para-frango1kg.webp",
	},
	{
		slug: "amendoim-runner-1-kg",
		name: "Amendoim Runner 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/amedoim-runner-1kg.webp",
	},
	{
		slug: "aveia-em-flocos-finos-1-kg",
		name: "Aveia em Flocos Finos 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/aveia-em-flocos-finos-1kg.webp",
	},
	{
		slug: "caldo-de-carne-1-kg",
		name: "Caldo de Carne 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/caldo-de-carne-1kg.webp",
	},
	{
		slug: "farelo-de-aveia-1-kg",
		name: "Farelo de Aveia 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/farelo-de-aveia-1kg.webp",
	},
	{
		slug: "lemon-pepper-1-kg",
		name: "Lemon Pepper 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/lemmon-pepper-1kg.webp",
	},
	{
		slug: "tempero-ana-maria-1-kg",
		name: "Tempero Ana Maria 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/tempero-ana-maria-1kg.webp",
	},
	{
		slug: "tempero-edu-guedes-1-kg",
		name: "Tempero Edu Guedes 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/tempero-edu-guedes-1kg.webp",
	},
	{
		slug: "tempero-pega-marido-1-kg",
		name: "Tempero Pega Marido 1 kg",
		familySlug: "institucional",
		family: "Institucional",
		image: "/images/products/institucional/tempero-pega-marido-1kg.webp",
	},
	{
		slug: "alho-triturado-200-g",
		name: "Alho Triturado 200 g",
		familySlug: "molhos-e-pastas",
		family: "Molhos e Pastas",
		image: "/images/products/molhos-e-pastas/alho-triturado-200g.webp",
	},
	{
		slug: "alho-triturado-jorge-batista-200-g",
		name: "Alho Triturado Jorge Batista 200 g",
		familySlug: "molhos-e-pastas",
		family: "Molhos e Pastas",
		image:
			"/images/products/molhos-e-pastas/alho-triturado-jorge-batista-200g.webp",
	},
	{
		slug: "molho-de-alho-300-ml",
		name: "Molho de Alho 300 ml",
		familySlug: "molhos-e-pastas",
		family: "Molhos e Pastas",
		image: "/images/products/molhos-e-pastas/molho-de-alho-300ml.webp",
	},
	{
		slug: "molho-de-alho-500-ml",
		name: "Molho de Alho 500 ml",
		familySlug: "molhos-e-pastas",
		family: "Molhos e Pastas",
		image: "/images/products/molhos-e-pastas/molho-de-alho-500ml.webp",
	},
	{
		slug: "molho-de-alho-jorge-batista-1-l",
		name: "Molho de Alho Jorge Batista 1 L",
		familySlug: "molhos-e-pastas",
		family: "Molhos e Pastas",
		image:
			"/images/products/molhos-e-pastas/molho-de-alho-jorge-batista-1-litro.webp",
	},
	{
		slug: "molho-de-alho-jorge-batista-300-ml",
		name: "Molho de Alho Jorge Batista 300 ml",
		familySlug: "molhos-e-pastas",
		family: "Molhos e Pastas",
		image:
			"/images/products/molhos-e-pastas/molho-de-alho-jorge-batista-300ml.webp",
	},
	{
		slug: "molho-de-alho-jorge-batista-500-ml",
		name: "Molho de Alho Jorge Batista 500 ml",
		familySlug: "molhos-e-pastas",
		family: "Molhos e Pastas",
		image:
			"/images/products/molhos-e-pastas/molho-de-alho-jorge-batista-500ml.webp",
	},
	{
		slug: "gergelim-preto",
		name: "Gergelim Preto",
		familySlug: "sementes-e-graos-naturais",
		family: "Sementes e Grãos Naturais",
		image:
			"/images/products/sementes-e-graos-naturais/sachet-gergelim-preto.webp",
	},
	{
		slug: "gergelim-branco",
		name: "Gergelim Branco",
		familySlug: "sementes-e-graos-naturais",
		family: "Sementes e Grãos Naturais",
		image:
			"/images/products/sementes-e-graos-naturais/sachet-gergelin-branco.webp",
	},
	{
		slug: "linhaca-dourada",
		name: "Linhaça Dourada",
		familySlug: "sementes-e-graos-naturais",
		family: "Sementes e Grãos Naturais",
		image:
			"/images/products/sementes-e-graos-naturais/sachet-linhaca-dourada.webp",
	},
	{
		slug: "linhaca-marrom",
		name: "Linhaça Marrom",
		familySlug: "sementes-e-graos-naturais",
		family: "Sementes e Grãos Naturais",
		image:
			"/images/products/sementes-e-graos-naturais/sachet-linhaca-marrom.webp",
	},
	{
		slug: "semente-de-abobora",
		name: "Semente de Abóbora",
		familySlug: "sementes-e-graos-naturais",
		family: "Sementes e Grãos Naturais",
		image:
			"/images/products/sementes-e-graos-naturais/sachet-semente-de-abobora.webp",
	},
	{
		slug: "semente-de-chia",
		name: "Semente de Chia",
		familySlug: "sementes-e-graos-naturais",
		family: "Sementes e Grãos Naturais",
		image:
			"/images/products/sementes-e-graos-naturais/sachet-semente-de-chia.webp",
	},
	{
		slug: "semente-de-girassol-sem-casca",
		name: "Semente de Girassol sem Casca",
		familySlug: "sementes-e-graos-naturais",
		family: "Sementes e Grãos Naturais",
		image:
			"/images/products/sementes-e-graos-naturais/sachet-semente-de-girassol-sem-casca.webp",
	},
	{
		slug: "alho-em-po",
		name: "Alho em Pó",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-alho-em-po.webp",
	},
	{
		slug: "cebola-em-po",
		name: "Cebola em Pó",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-cebola-po.webp",
	},
	{
		slug: "cebola-salsa-e-alho",
		name: "Cebola Salsa e Alho",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-cebola-salsa-e-alho.webp",
	},
	{
		slug: "chimichurri-com-pimenta",
		name: "Chimichurri com Pimenta",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-chimichuri-com-pimenta.webp",
	},
	{
		slug: "chimichurri-sem-pimenta",
		name: "Chimichurri sem Pimenta",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-chimichuri-sem-pimenta.webp",
	},
	{
		slug: "coloral",
		name: "Coloral",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-coloral.webp",
	},
	{
		slug: "cominho-moido",
		name: "Cominho Moído",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-cominho-moido.webp",
	},
	{
		slug: "curcuma",
		name: "Cúrcuma",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-curcuma.webp",
	},
	{
		slug: "lemon-pepper",
		name: "Lemon Pepper",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-lemom-pepper.webp",
	},
	{
		slug: "paprica-defumada",
		name: "Páprica Defumada",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-paprica-defumada.webp",
	},
	{
		slug: "paprica-doce",
		name: "Páprica Doce",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-paprica-doce.webp",
	},
	{
		slug: "paprica-picante",
		name: "Páprica Picante",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-paprica-picante.webp",
	},
	{
		slug: "pimenta-do-reino-em-po",
		name: "Pimenta do Reino em Pó",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-pimenta-do-reino-em-po.webp",
	},
	{
		slug: "tempero-do-chef",
		name: "Tempero do Chef",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-tempero-do-chef.webp",
	},
	{
		slug: "tempero-para-feijao",
		name: "Tempero para Feijão",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-tempero-para-feijao.webp",
	},
	{
		slug: "tempero-para-frango",
		name: "Tempero para Frango",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-tempero-para-frango.webp",
	},
	{
		slug: "tempero-pega-marido",
		name: "Tempero Pega Marido",
		familySlug: "temperos-em-po",
		family: "Temperos em Pó",
		image: "/images/products/temperos-em-po/sachet-tempero-pega-marido.webp",
	},
	{
		slug: "amaciante-500-ml",
		name: "Amaciante 500 ml",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image: "/images/products/temperos-liquidos-prontos/amaciante-500ml.webp",
	},
	{
		slug: "tempero-caseiro-300-ml",
		name: "Tempero Caseiro 300 ml",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image:
			"/images/products/temperos-liquidos-prontos/tempero-caseiro-300ml.webp",
	},
	{
		slug: "tempero-caseiro-500-ml",
		name: "Tempero Caseiro 500 ml",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image:
			"/images/products/temperos-liquidos-prontos/tempero-caseiro-500ml.webp",
	},
	{
		slug: "tempero-completo-jorge-batista-300-ml",
		name: "Tempero Completo Jorge Batista 300 ml",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image:
			"/images/products/temperos-liquidos-prontos/tempero-completo-jorge-batista-300ml.webp",
	},
	{
		slug: "tempero-completo-jorge-batista-500-ml",
		name: "Tempero Completo Jorge Batista 500 ml",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image:
			"/images/products/temperos-liquidos-prontos/tempero-completo-jorge-batista-500ml.webp",
	},
	{
		slug: "tempero-completo-jorge-batista",
		name: "Tempero Completo Jorge Batista",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image:
			"/images/products/temperos-liquidos-prontos/tempero-completo-jorge-batista.webp",
	},
	{
		slug: "tempero-especial-300-ml",
		name: "Tempero Especial 300 ml",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image:
			"/images/products/temperos-liquidos-prontos/tempero-especial-300ml.webp",
	},
	{
		slug: "tempero-especial-500-ml",
		name: "Tempero Especial 500 ml",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image:
			"/images/products/temperos-liquidos-prontos/tempero-especial-500ml.webp",
	},
	{
		slug: "tempero-especial-900-ml",
		name: "Tempero Especial 900 ml",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image:
			"/images/products/temperos-liquidos-prontos/tempero-especial-900ml.webp",
	},
	{
		slug: "tempero-frango-300-ml",
		name: "Tempero Frango 300 ml",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image:
			"/images/products/temperos-liquidos-prontos/tempero-frango-300ml.webp",
	},
	{
		slug: "tempero-frango-500-ml",
		name: "Tempero Frango 500 ml",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image:
			"/images/products/temperos-liquidos-prontos/tempero-frango-500ml.webp",
	},
	{
		slug: "tempero-tradicional-200-ml",
		name: "Tempero Tradicional 200 ml",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image:
			"/images/products/temperos-liquidos-prontos/tempero-tradicional-200ml.webp",
	},
	{
		slug: "tempero-tradicional-300-ml",
		name: "Tempero Tradicional 300 ml",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image:
			"/images/products/temperos-liquidos-prontos/tempero-tradicional-300ml.webp",
	},
	{
		slug: "tempero-tradicional-500-ml",
		name: "Tempero Tradicional 500 ml",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image:
			"/images/products/temperos-liquidos-prontos/tempero-tradicional-500ml.webp",
	},
	{
		slug: "tempero-tradicional-900-ml",
		name: "Tempero Tradicional 900 ml",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image:
			"/images/products/temperos-liquidos-prontos/tempero-tradicional-900ml.webp",
	},
	{
		slug: "amaciante-300-ml",
		name: "Amaciante 300 ml",
		familySlug: "temperos-liquidos-prontos",
		family: "Temperos Líquidos Prontos",
		image: "/images/products/temperos-liquidos-prontos/amaciante-300ml.webp",
	},
] as const;

export function getFamilyBySlug(slug: string): ProductFamily | undefined {
	return PRODUCT_FAMILIES.find((family) => family.slug === slug);
}

export function getProductsByFamily(familySlug: string): readonly Product[] {
	return PRODUCTS.filter((product) => product.familySlug === familySlug);
}
